-- Adds production formulas, automated production cost calculation, and production lots.

create table if not exists public.produccion_formulas (
  id integer generated by default as identity primary key,
  producto_id integer not null references public.productos(id),
  notas text,
  activo boolean not null default true,
  usuario_id integer references public.usuarios(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.produccion_formula_insumos (
  id integer generated by default as identity primary key,
  formula_id integer not null references public.produccion_formulas(id) on delete cascade,
  producto_insumo_id integer not null references public.productos(id),
  cantidad numeric(12,4) not null check (cantidad > 0),
  created_at timestamptz default now()
);

create table if not exists public.lotes_produccion (
  id integer generated by default as identity primary key,
  codigo_lote varchar(40) not null unique,
  producto_id integer not null references public.productos(id),
  cantidad_producida numeric(12,4) not null check (cantidad_producida > 0),
  costo_total numeric(12,2) not null default 0.00,
  costo_unitario numeric(12,4) not null default 0.0000,
  estado varchar(20) not null default 'cerrado' check (estado in ('borrador','cerrado','cancelado')),
  notas text,
  usuario_id integer references public.usuarios(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.lotes_produccion_insumos (
  id integer generated by default as identity primary key,
  lote_id integer not null references public.lotes_produccion(id) on delete cascade,
  producto_insumo_id integer not null references public.productos(id),
  cantidad numeric(12,4) not null check (cantidad > 0),
  costo_unitario numeric(12,4) not null default 0.0000,
  subtotal numeric(12,2) not null default 0.00
);

alter table public.movimientos_inventario
  add column if not exists lote_produccion_id integer references public.lotes_produccion(id);

create index if not exists idx_produccion_formulas_producto_id on public.produccion_formulas(producto_id);
create unique index if not exists uq_produccion_formula_activa_producto
  on public.produccion_formulas(producto_id)
  where activo = true;
create index if not exists idx_produccion_formula_insumos_formula_id on public.produccion_formula_insumos(formula_id);
create index if not exists idx_lotes_produccion_producto_id on public.lotes_produccion(producto_id);
create index if not exists idx_lotes_produccion_created_at on public.lotes_produccion(created_at);
create index if not exists idx_lotes_produccion_insumos_lote_id on public.lotes_produccion_insumos(lote_id);
create index if not exists idx_movimientos_lote_produccion_id on public.movimientos_inventario(lote_produccion_id);

drop trigger if exists trg_produccion_formulas_updated_at on public.produccion_formulas;
create trigger trg_produccion_formulas_updated_at before update on public.produccion_formulas for each row execute function public.set_updated_at();

drop trigger if exists trg_lotes_produccion_updated_at on public.lotes_produccion;
create trigger trg_lotes_produccion_updated_at before update on public.lotes_produccion for each row execute function public.set_updated_at();

alter table public.produccion_formulas enable row level security;
alter table public.produccion_formula_insumos enable row level security;
alter table public.lotes_produccion enable row level security;
alter table public.lotes_produccion_insumos enable row level security;

insert into public.roles (nombre, descripcion, permisos)
values ('produccion', 'Supervisor de producción con acceso a fórmulas, costos y lotes', '["inventario","produccion","proveedores"]'::jsonb)
on conflict (nombre) do nothing;
