-- Orchid POS initial schema for Supabase/PostgreSQL.
-- Generated from the current local MySQL schema.
-- WARNING: this resets the Supabase public schema.
-- It deletes all existing tables, views, functions, triggers, policies, and data in public.

do $$
begin
  if current_setting('transaction_read_only') = 'on' then
    raise exception 'Esta migracion debe ejecutarse en la base principal de Supabase, no en una conexion/transaccion de solo lectura.';
  end if;
end;
$$;

drop schema if exists public cascade;
create schema public;

grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on schema public to postgres, service_role;
alter default privileges in schema public grant all on tables to postgres, service_role;
alter default privileges in schema public grant all on sequences to postgres, service_role;
alter default privileges in schema public grant all on functions to postgres, service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.roles (
  id integer generated by default as identity primary key,
  nombre varchar(50) not null unique,
  descripcion text,
  permisos jsonb,
  created_at timestamptz default now()
);

create table public.usuarios (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null,
  email varchar(150) not null unique,
  password varchar(255) not null,
  rol_id integer not null references public.roles(id),
  activo boolean default true,
  ultimo_login timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.clientes (
  id integer generated by default as identity primary key,
  nombre varchar(150) not null,
  email varchar(150),
  telefono varchar(20),
  direccion text,
  rfc varchar(20),
  tipo varchar(30) default 'publico_general' check (tipo in ('publico_general','frecuente','mayorista')),
  descuento_default numeric(5,2) default 0.00,
  notas text,
  activo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz,
  facturapi_id varchar(100),
  regimen_fiscal varchar(10),
  codigo_postal varchar(10),
  uso_cfdi varchar(10) default 'G03'
);

create table public.proveedores (
  id integer generated by default as identity primary key,
  nombre varchar(150) not null,
  contacto varchar(100),
  email varchar(150),
  telefono varchar(20),
  direccion text,
  rfc varchar(20),
  notas text,
  activo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.categorias (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null,
  descripcion text,
  imagen_url varchar(255),
  activo boolean default true,
  created_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.productos (
  id integer generated by default as identity primary key,
  codigo varchar(50) not null unique,
  nombre varchar(200) not null,
  descripcion text,
  categoria_id integer not null references public.categorias(id),
  proveedor_id integer references public.proveedores(id),
  tipo_producto varchar(20) not null default 'venta' check (tipo_producto in ('venta','insumo')),
  precio_compra numeric(10,2) not null default 0.00,
  precio_venta numeric(10,2) not null,
  stock integer not null default 0,
  stock_minimo integer not null default 5,
  unidad varchar(30) default 'pieza',
  imagen_url varchar(255),
  activo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz,
  codigo_sat varchar(20) default '01010101',
  unidad_sat varchar(10) default 'H87'
);

create table public.produccion_formulas (
  id integer generated by default as identity primary key,
  producto_id integer not null references public.productos(id),
  notas text,
  activo boolean not null default true,
  usuario_id integer references public.usuarios(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.produccion_formula_insumos (
  id integer generated by default as identity primary key,
  formula_id integer not null references public.produccion_formulas(id) on delete cascade,
  producto_insumo_id integer not null references public.productos(id),
  cantidad numeric(12,4) not null check (cantidad > 0),
  created_at timestamptz default now()
);

create table public.lotes_produccion (
  id integer generated by default as identity primary key,
  codigo_lote varchar(40) not null unique,
  producto_id integer not null references public.productos(id),
  cantidad_producida numeric(12,4) not null check (cantidad_producida > 0),
  costo_total numeric(12,2) not null default 0.00,
  costo_unitario numeric(12,4) not null default 0.0000,
  estado varchar(20) not null default 'cerrado' check (estado in ('borrador','cerrado','cancelado')),
  notas text,
  usuario_id integer references public.usuarios(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.lotes_produccion_insumos (
  id integer generated by default as identity primary key,
  lote_id integer not null references public.lotes_produccion(id) on delete cascade,
  producto_insumo_id integer not null references public.productos(id),
  cantidad numeric(12,4) not null check (cantidad > 0),
  costo_unitario numeric(12,4) not null default 0.0000,
  subtotal numeric(12,2) not null default 0.00
);

create table public.cajas (
  id integer generated by default as identity primary key,
  usuario_id integer not null references public.usuarios(id),
  monto_apertura numeric(10,2) not null default 0.00,
  monto_cierre numeric(10,2),
  monto_ventas_efectivo numeric(10,2) default 0.00,
  monto_ventas_tarjeta numeric(10,2) default 0.00,
  monto_ventas_transferencia numeric(10,2) default 0.00,
  monto_entradas numeric(10,2) default 0.00,
  monto_salidas numeric(10,2) default 0.00,
  monto_esperado numeric(10,2) default 0.00,
  monto_real numeric(10,2),
  diferencia numeric(10,2),
  estado varchar(20) default 'abierta' check (estado in ('abierta','cerrada')),
  notas text,
  fecha_apertura timestamptz default now(),
  fecha_cierre timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.ventas (
  id integer generated by default as identity primary key,
  folio varchar(20) not null unique,
  cliente_id integer references public.clientes(id),
  usuario_id integer not null references public.usuarios(id),
  caja_id integer references public.cajas(id),
  subtotal numeric(10,2) not null default 0.00,
  descuento numeric(10,2) not null default 0.00,
  iva numeric(10,2) not null default 0.00,
  total numeric(10,2) not null default 0.00,
  metodo_pago varchar(20) default 'efectivo' check (metodo_pago in ('efectivo','tarjeta','transferencia','mixto')),
  monto_pagado numeric(10,2) default 0.00,
  cambio numeric(10,2) default 0.00,
  estado varchar(20) default 'completada' check (estado in ('completada','cancelada','pendiente')),
  notas text,
  referencia_pago varchar(255),
  created_at timestamptz default now(),
  factura_id varchar(100),
  factura_url varchar(255)
);

create table public.detalle_ventas (
  id integer generated by default as identity primary key,
  venta_id integer not null references public.ventas(id) on delete cascade,
  producto_id integer not null references public.productos(id),
  cantidad integer not null,
  precio_unitario numeric(10,2) not null,
  descuento numeric(5,2) default 0.00,
  subtotal numeric(10,2) not null,
  created_at timestamptz default now()
);

create table public.apartados (
  id integer generated by default as identity primary key,
  folio varchar(30) not null unique,
  cliente_id integer not null references public.clientes(id),
  usuario_id integer not null references public.usuarios(id),
  subtotal numeric(12,2) not null default 0.00,
  descuento numeric(12,2) not null default 0.00,
  iva numeric(12,2) not null default 0.00,
  total numeric(12,2) not null default 0.00,
  monto_pagado numeric(12,2) not null default 0.00,
  saldo_pendiente numeric(12,2) not null default 0.00,
  estado varchar(20) default 'activo' check (estado in ('activo','completado','cancelado','vencido','entregado')),
  fecha_limite date,
  notas text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.detalle_apartados (
  id integer generated by default as identity primary key,
  apartado_id integer not null references public.apartados(id) on delete cascade,
  producto_id integer not null references public.productos(id),
  cantidad integer not null default 1,
  precio_unitario numeric(12,2) not null,
  descuento numeric(5,2) not null default 0.00,
  subtotal numeric(12,2) not null default 0.00
);

create table public.pagos_apartado (
  id integer generated by default as identity primary key,
  apartado_id integer not null references public.apartados(id) on delete cascade,
  usuario_id integer not null references public.usuarios(id),
  monto numeric(12,2) not null,
  metodo_pago varchar(20) not null default 'efectivo' check (metodo_pago in ('efectivo','tarjeta','transferencia')),
  notas varchar(255),
  referencia_pago varchar(255),
  created_at timestamptz default now()
);

create table public.beneficios (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null,
  descripcion text,
  tipo varchar(20) not null check (tipo in ('puntos','comision','descuento','bono')),
  valor numeric(10,2) not null,
  target_type varchar(20) not null check (target_type in ('cliente','empleado')),
  is_automatic boolean default false,
  activo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.beneficios_asignados (
  id integer generated by default as identity primary key,
  beneficio_id integer not null references public.beneficios(id) on delete cascade,
  entidad_id integer not null,
  entidad_type varchar(20) not null check (entidad_type in ('cliente','empleado')),
  fecha_asignacion timestamptz default now()
);

create table public.compras (
  id integer generated by default as identity primary key,
  proveedor_id integer not null references public.proveedores(id),
  usuario_id integer not null references public.usuarios(id),
  folio varchar(20) not null unique,
  total numeric(10,2) not null default 0.00,
  saldo_pendiente numeric(10,2) not null default 0.00,
  estado varchar(20) default 'pendiente' check (estado in ('pagada','pendiente','cancelada')),
  notas text,
  fecha_compra date not null,
  fecha_vencimiento date,
  created_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.detalle_compras (
  id integer generated by default as identity primary key,
  compra_id integer not null references public.compras(id),
  producto_id integer not null references public.productos(id),
  cantidad integer not null,
  costo_unitario numeric(10,2) not null
);

create table public.pagos_compras (
  id integer generated by default as identity primary key,
  compra_id integer not null references public.compras(id),
  usuario_id integer not null references public.usuarios(id),
  monto numeric(10,2) not null,
  metodo_pago varchar(20) not null check (metodo_pago in ('efectivo','tarjeta','transferencia')),
  notas text,
  created_at timestamptz default now()
);

create table public.movimientos_inventario (
  id integer generated by default as identity primary key,
  producto_id integer not null references public.productos(id),
  tipo varchar(20) not null check (tipo in ('entrada','salida','ajuste','venta','devolucion','apartado')),
  cantidad integer not null,
  stock_anterior integer not null,
  stock_nuevo integer not null,
  motivo varchar(255),
  sospechoso boolean default false,
  usuario_id integer references public.usuarios(id),
  venta_id integer references public.ventas(id),
  compra_id integer references public.compras(id),
  proveedor_id integer references public.proveedores(id),
  costo_unitario numeric(10,2),
  lote_produccion_id integer references public.lotes_produccion(id),
  created_at timestamptz default now()
);

create table public.categorias_gastos (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null,
  descripcion varchar(255),
  activo boolean default true,
  created_at timestamptz default now()
);

create table public.gastos (
  id integer generated by default as identity primary key,
  categoria_gasto_id integer not null references public.categorias_gastos(id),
  usuario_id integer not null references public.usuarios(id),
  monto numeric(10,2) not null,
  concepto varchar(255) not null,
  fecha date not null,
  metodo_pago varchar(20) default 'efectivo' check (metodo_pago in ('efectivo','tarjeta','transferencia')),
  comprobante_url varchar(255),
  created_at timestamptz default now()
);

create table public.movimientos_caja (
  id integer generated by default as identity primary key,
  caja_id integer not null references public.cajas(id) on delete cascade,
  usuario_id integer not null references public.usuarios(id),
  tipo varchar(20) not null check (tipo in ('entrada','salida')),
  monto numeric(10,2) not null,
  concepto varchar(255) not null,
  fecha timestamptz default now()
);

create table public.configuracion (
  id integer generated by default as identity primary key,
  clave varchar(100) not null unique,
  valor text,
  updated_at timestamptz default now()
);

create index if not exists idx_productos_categoria_id on public.productos(categoria_id);
create index if not exists idx_productos_proveedor_id on public.productos(proveedor_id);
create index if not exists idx_productos_tipo_producto on public.productos(tipo_producto);
create index if not exists idx_produccion_formulas_producto_id on public.produccion_formulas(producto_id);
create unique index if not exists uq_produccion_formula_activa_producto on public.produccion_formulas(producto_id) where activo = true;
create index if not exists idx_produccion_formula_insumos_formula_id on public.produccion_formula_insumos(formula_id);
create index if not exists idx_lotes_produccion_producto_id on public.lotes_produccion(producto_id);
create index if not exists idx_lotes_produccion_created_at on public.lotes_produccion(created_at);
create index if not exists idx_lotes_produccion_insumos_lote_id on public.lotes_produccion_insumos(lote_id);
create index if not exists idx_ventas_cliente_id on public.ventas(cliente_id);
create index if not exists idx_ventas_usuario_id on public.ventas(usuario_id);
create index if not exists idx_ventas_caja_id on public.ventas(caja_id);
create index if not exists idx_detalle_ventas_venta_id on public.detalle_ventas(venta_id);
create index if not exists idx_detalle_ventas_producto_id on public.detalle_ventas(producto_id);
create index if not exists idx_movimientos_producto on public.movimientos_inventario(producto_id);
create index if not exists idx_movimientos_created on public.movimientos_inventario(created_at);
create index if not exists idx_movimientos_usuario_id on public.movimientos_inventario(usuario_id);
create index if not exists idx_movimientos_venta_id on public.movimientos_inventario(venta_id);
create index if not exists idx_movimientos_compra_id on public.movimientos_inventario(compra_id);
create index if not exists idx_movimientos_proveedor_id on public.movimientos_inventario(proveedor_id);
create index if not exists idx_movimientos_lote_produccion_id on public.movimientos_inventario(lote_produccion_id);
create index if not exists idx_apartados_cliente_id on public.apartados(cliente_id);
create index if not exists idx_apartados_usuario_id on public.apartados(usuario_id);
create index if not exists idx_compras_proveedor_id on public.compras(proveedor_id);
create index if not exists idx_compras_usuario_id on public.compras(usuario_id);
create index if not exists idx_gastos_categoria_gasto_id on public.gastos(categoria_gasto_id);
create index if not exists idx_gastos_usuario_id on public.gastos(usuario_id);
create index if not exists idx_cajas_usuario_id on public.cajas(usuario_id);

drop trigger if exists trg_usuarios_updated_at on public.usuarios;
create trigger trg_usuarios_updated_at before update on public.usuarios for each row execute function public.set_updated_at();
drop trigger if exists trg_clientes_updated_at on public.clientes;
create trigger trg_clientes_updated_at before update on public.clientes for each row execute function public.set_updated_at();
drop trigger if exists trg_proveedores_updated_at on public.proveedores;
create trigger trg_proveedores_updated_at before update on public.proveedores for each row execute function public.set_updated_at();
drop trigger if exists trg_productos_updated_at on public.productos;
create trigger trg_productos_updated_at before update on public.productos for each row execute function public.set_updated_at();
drop trigger if exists trg_produccion_formulas_updated_at on public.produccion_formulas;
create trigger trg_produccion_formulas_updated_at before update on public.produccion_formulas for each row execute function public.set_updated_at();
drop trigger if exists trg_lotes_produccion_updated_at on public.lotes_produccion;
create trigger trg_lotes_produccion_updated_at before update on public.lotes_produccion for each row execute function public.set_updated_at();
drop trigger if exists trg_cajas_updated_at on public.cajas;
create trigger trg_cajas_updated_at before update on public.cajas for each row execute function public.set_updated_at();
drop trigger if exists trg_apartados_updated_at on public.apartados;
create trigger trg_apartados_updated_at before update on public.apartados for each row execute function public.set_updated_at();
drop trigger if exists trg_beneficios_updated_at on public.beneficios;
create trigger trg_beneficios_updated_at before update on public.beneficios for each row execute function public.set_updated_at();
drop trigger if exists trg_configuracion_updated_at on public.configuracion;
create trigger trg_configuracion_updated_at before update on public.configuracion for each row execute function public.set_updated_at();

create or replace view public.vista_productos_bajo_stock
with (security_invoker = true) as
select id, nombre, codigo, stock, stock_minimo, unidad
from public.productos
where activo = true and deleted_at is null and stock <= stock_minimo;

create or replace view public.vista_top_productos
with (security_invoker = true) as
select p.id, p.nombre, sum(dv.cantidad) as total_vendido, sum(dv.subtotal) as total_ingreso
from public.productos p
join public.detalle_ventas dv on p.id = dv.producto_id
join public.ventas v on dv.venta_id = v.id
where v.estado = 'completada'
group by p.id, p.nombre
order by total_vendido desc;

create or replace view public.vista_ventas_diarias
with (security_invoker = true) as
select ventas.created_at::date as fecha, count(*) as total_ventas, sum(total) as ingresos
from public.ventas
where estado = 'completada'
group by ventas.created_at::date
order by fecha desc;

insert into public.roles (id, nombre, descripcion, permisos)
values
  (1, 'admin', 'Administrador con acceso total', '["ventas","inventario","clientes","reportes","usuarios","proveedores"]'::jsonb),
  (2, 'vendedor', 'Puede realizar ventas y consultar inventario', '["ventas","inventario","clientes"]'::jsonb),
  (3, 'bodeguero', 'Gestión de inventario y proveedores', '["inventario","proveedores"]'::jsonb),
  (4, 'produccion', 'Supervisor de producción con acceso a fórmulas, costos y lotes', '["inventario","produccion","proveedores"]'::jsonb)
on conflict (id) do nothing;

insert into public.clientes (id, nombre, tipo, descuento_default, activo, uso_cfdi)
values (1, 'Público General', 'publico_general', 0.00, true, 'G03')
on conflict (id) do nothing;

insert into public.categorias_gastos (id, nombre, descripcion)
values
  (1, 'Renta', 'Pago de alquiler del local'),
  (2, 'Servicios', 'Luz, agua, internet, teléfono'),
  (3, 'Sueldos', 'Pago a empleados'),
  (4, 'Proveedores', 'Compras de mercancía o insumos'),
  (5, 'Impuestos', 'Pagos al SAT / Gobierno'),
  (6, 'Mantenimiento', 'Reparaciones y limpieza'),
  (7, 'Otros', 'Gastos no clasificados')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.roles', 'id'), greatest((select coalesce(max(id), 1) from public.roles), 1), true);
select setval(pg_get_serial_sequence('public.clientes', 'id'), greatest((select coalesce(max(id), 1) from public.clientes), 1), true);
select setval(pg_get_serial_sequence('public.categorias_gastos', 'id'), greatest((select coalesce(max(id), 1) from public.categorias_gastos), 1), true);

alter table public.roles enable row level security;
alter table public.usuarios enable row level security;
alter table public.clientes enable row level security;
alter table public.proveedores enable row level security;
alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.produccion_formulas enable row level security;
alter table public.produccion_formula_insumos enable row level security;
alter table public.lotes_produccion enable row level security;
alter table public.lotes_produccion_insumos enable row level security;
alter table public.cajas enable row level security;
alter table public.ventas enable row level security;
alter table public.detalle_ventas enable row level security;
alter table public.apartados enable row level security;
alter table public.detalle_apartados enable row level security;
alter table public.pagos_apartado enable row level security;
alter table public.beneficios enable row level security;
alter table public.beneficios_asignados enable row level security;
alter table public.compras enable row level security;
alter table public.detalle_compras enable row level security;
alter table public.pagos_compras enable row level security;
alter table public.movimientos_inventario enable row level security;
alter table public.categorias_gastos enable row level security;
alter table public.gastos enable row level security;
alter table public.movimientos_caja enable row level security;
alter table public.configuracion enable row level security;
